server:
  port: 8081
#
spring:
  application:
    name: gateway-server
#  cloud:
#    gateway:
#      routes:
#        #路径匹配
#        - id: find
#          uri: https://blog.csdn.net
#          predicates:
#            - Path=/common
#        - id: service-a-route
#          uri: lb://service-a # 使用服务发现指向服务A
#          predicates:
#            - Path=/service-a/**
#          filters:
#            - StripPrefix=1
#        - id: service-b-route
#          uri: http://localhost:8081 # 直接指向本地服务B
#          predicates:
#            - Path=/service-b/**
#          filters:
#            - StripPrefix=1
management:
  endpoints:
    web:
      exposure:
        include: '*' # 允许所有Actuator端点通过HTTP访问
