server:
  port: 9089


spring:
  application:
    name: gateway-service-local
  cloud:
    gateway:
      routes:
        - id: local-business
          uri: http://localhost:11301/business/
          predicates:
            - Path=/gateway/api/v1/business/**
          filters:
            - StripPrefix=3

gateway:
  filter:
    responseFilter: true


dubbo:
  application:
    logger: slf4j
    name: ${spring.application.name}
    id: ${spring.application.name}
    register-mode: instance
    qos-enable: false
  registry:
    address: nacos://172.16.224.100:8848
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  scan:
    base-packages: com.hh
#  provider:
#    filter: -exception,requestLogFilter,dubboExceptionFilter