server:
  port: 8081
#
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: user_route
          uri: lb://user-service # 假设用户服务ID为user-service
          predicates:
            - Path=/api/users/**
    nacos:
      discovery:
        server-addr: localhost:8848 # Nacos作为服务发现的地址
      config:
        server-addr: localhost:8848 # Nacos作为配置中心的地址
        namespace: your_namespace # 如果有命名空间，请填写
        group: DEFAULT_GROUP # 配置分组，默认即可
        file-extension: yml # 指定配置文件类型
        refresh-enabled: true # 开启配置自动刷新

dubbo:
  registry:
    address: nacos://172.16.224.100:8848
  application:
    logger: slf4j
    name: gateway-server
    qos-enable: false
    register-mode: instance # 指定仅应用级注册
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  consumer:
    check: false # 可选，关闭消费者端启动时检查提供者是否存在
    retries: 0
  scan:
    base-packages: com.aurora

management:
  endpoints:
    web:
      exposure:
        include: '*' # 允许所有Actuator端点通过HTTP访问
